<a href="https://colab.research.google.com/github/Sudarshan0851/python_notes_by_sudarshan/blob/main/Numpy_11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#30-03-2026

**Introduction to Numpy**

In [ ]:
l = [1,2,3,4,5,6]
l2 = [7,8,9,10,11,12]
print(l+l2) #list concatenation
new = []

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]


In [ ]:
#what is Numpy?
#it is a core library for scientific computation in python
#The central object in numpy is "Numpy Array's"
#what is Numpy Array?
#Array's are high performence, multidimensional object which is designed for mathematical operation


In [ ]:
#How many types of array's do we have or Howmany type of data structures in Numpy?
#There are 3 types
#1.1D-array:- having only axis 0 (rows) and on columns
#2.2D-array:- having both axis 0(rows) and axis 1(column)
#3.3D-array:- multidimensional array's


**What are all numerical operations acheived easily with numpy**

1. Dot product/ Inner product
2. Matrix multiplication
3. solving the linear systems
4. statistics
5. inverse
6. choose random numbers
7. determinent


In [ ]:
#pip is a python package manager used to install pachages into python
!pip install numpy

In [ ]:
import numpy as np

In [ ]:
#check the version of numpy
np.__version__

'2.0.2'

**The central object in numpy is Numpy array**

In [ ]:
l = [1,2,3,4,5,6]
print(type(l))
print(l)

<class 'list'>
[1, 2, 3, 4, 5, 6]


In [ ]:
#convert above list into array
a = np.array(l)
print(a)
print(type(a))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [ ]:
#find the number rows and columns in above  -->np.shape
print(a.shape)
#find the dimensionality of an array? -->np.ndim
print(a.ndim)
#find the element data types inside array -->np.dtype
print(a.dtype)
#find the numbers of elements in the array --> np.size --> no of rows * no of column
print(a.size)
#find the memory occupency of each elemnt in above array --> np.itemsize  --> bytes
print(a.itemsize)

(6,)
1
int64
6
8


**essential methods in Numpy to access the data**

In [ ]:
#Numpy is Ordered --> elements have index values
a = np.array([1,2,3,4,5,6,7,8,9])
#print 5
print(a[4])

5


In [ ]:
#print numbers from 3,4,5,6,7
print(a[2:7])
#print the even index values
print(a[1:10:2])

[3 4 5 6 7]
[2 4 6 8]


In [ ]:
#reverse array a
print(a[::-1])

[9 8 7 6 5 4 3 2 1]


In [ ]:
#replace 7 with 10
a[6] = 10
print(a)

[ 1  2  3  4  5  6 10  8  9]


In [ ]:
#array's are immutable means we cannot add and remove items in array but we can replace the items

scaler vs Vector

scaler : it has only one value -->  a = 10,age = 25

vector :- collection of number  --> [1,2,3]

In [ ]:
#np.array()  --> to create an array
#np.ndim
#np.dtype
#np.size

#31-03-2026

**element wise maths operations**

In [ ]:
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a+b)

[5 7 9]


In [ ]:
a = np.array([1,2,3]) #broadcasting method
b = np.array([4])
print(a+b)
#Note:when we apply arthematic operation on array's must be same size  or
#if single element array applys any arthematic operation on different shape array this mechanism is known as Broadcasting method
#applying the addition arthematic operation on array's of same shape is known as Vector addition.

[5 6 7]


**Dot Product** --> is defined as vector multiplication of array's and sum of the result

--> what are rules to apply the dot product?
  
  --> array's must be in same shape  



In [ ]:
a = np.array([4,5])
b = np.array([1,2])
dot = 0
for i in range(len(a)):
  dot =  dot+a[i]*b[i]
print(dot)

14


In [ ]:
c = np.dot(a,b)
print(c)

14


In [ ]:
d = a.dot(b)
print(d)

14


In [ ]:
e = a @ b
print(e)

14


#2D Array's

In [ ]:
#create a 2d array from below list
l = [1,2,3,4,5,6,7,8,9]
a = np.array([l])
#print(a)
print(a.shape)
print(a.ndim)

(1, 9)
2


In [ ]:
#create an array 2 rows and 3 columns
b = np.array([[1,2,3],[4,5,6]])
print(b)
print(b.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [ ]:
#create an array of 3 rows and 4 columns?
c = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(c)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
#syntax to access the data -->  [row_index, col_index]
#print the first row elements
# print(c[0:2])
#print "6" from above array
print(c[1,1])
#print the 12 from above array
print(c[2,3])

6
12


**Dot product on 2D rray is known as matrix mutliplication**

rules to apply dot product in 2D arrays

In [ ]:
a = np.array([[1,2],[3,4]])
b = np.array([[3,4],[5,6]])
print(np.dot(a,b))

[[13 16]
 [29 36]]


In [ ]:
print(a)
print(b)

[[1 2]
 [3 4]]
[[3 4]
 [5 6]]


In [ ]:
a = np.array([[3,4,5],[7,8,9]])
b = np.array([[10,11,12],[13,14,15]])
#find the dot product for above array
print(a@b.T)
# print(a)
# print(b)
#In 2D-array the number columns is equals to the numbers rows in 2nd arrays

[[134 170]
 [266 338]]


In [ ]:
print(a)

[[3 4 5]
 [7 8 9]]


In [ ]:
print(b.T)

[[10 13]
 [11 14]
 [12 15]]


In [ ]:
#Transpose --> converst rows to columns and column to rows

In [ ]:
c = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
#find the min element from above array "c"
print(c)
print(c.min())
print(c.max())
print(c.sum())
print(np.diag(c)) #find the diagonal data from array "c"

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
1
12
78
[ 1  6 11]


#03-04-2026

**Boolean Indexing**

In [ ]:
import numpy as np

In [ ]:
a = np.array([[1,2],[3,4],[5,6]])
#from the above array check the values greater then 2
print(a.shape)
print(a.ndim)
print(a>2)

(3, 2)
2
[[False False]
 [ True  True]
 [ True  True]]


In [ ]:
l = [1,2,3,4,5,6]
#check the number greater then 2
for i in l:
  print(i>2)

False
False
True
True
True
True


Apply condition in array's

Np.where(logic,true,false)

In [ ]:
a = np.array([[1,2],[3,4],[5,6]])
#if the number more then 2 print those numbers others wise print -1
print(np.where(a>2,a,-1))

[[-1 -1]
 [ 3  4]
 [ 5  6]]


In [ ]:
b = np.array([10,20,21,16,13,17,19])
#apply the condition and check the evenumbers in above data
#if even print even numbers otherwise print -1
print(np.where(b%2==0,b,-1))

[10 20 -1 16 -1 -1 -1]


In [ ]:
#from above problem compute the indexes where the condition is true
#np.argwhere(logic)
print(np.argwhere(b%2==0).flatten())  #flatten is used to print output in 1D format

[0 1 3]


**reshaping array's**

In [ ]:
a = np.array([0,1,2,3,4,5,6,7,8,9])
#convert the above array in to 2 rows and 5 columns
#np.reshape(row,col)
print(a.reshape(2,5))

[[0 1 2 3 4]
 [5 6 7 8 9]]


**ADD new axis to the array's**

--> np.newaxis

In [ ]:
a = np.array([0,1,2,3,4,5,6,7,8,9])
print(a.shape)

(10,)


In [ ]:
print(a[np.newaxis,:])

[[0 1 2 3 4 5 6 7 8 9]]


In [ ]:
#add the new axis at the column level
print(a[:,np.newaxis])

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


**Concatenation of array's**

In [ ]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
#join the array A and B
c = np.concatenate((a,b),axis=1)
print(c)

[[1 2 5 6]
 [3 4 7 8]]


*Hstack :- adds the stack array in horzental seqhence**

In [ ]:
d = np.hstack((a,b))
print(d)

[1 2 3 1 2 6]


*Vstack adds the stack array in sequence vertically*

In [ ]:
e = np.vstack((a,b))
print(e)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


**copying** --> ithelps you when we make changes in new array it doesnot impact on the old array

In [ ]:
a = np.array([1,2,3])
b = a.copy()
b[2]=6
print(a)
print(b)

[1 2 3]
[1 2 6]


**Generating array's**

In [ ]:
#generate an array of zeros with 2 rows and 3 columns
a = np.zeros((2,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
print(np.zeros(5))

[0. 0. 0. 0. 0.]


In [ ]:
#generate an array of ones
b = np.ones((2,3))
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
#generate an array of specific number with 5 rows and 3 columns
c = np.full((5,3),6)
print(c)

[[6 6 6]
 [6 6 6]
 [6 6 6]
 [6 6 6]
 [6 6 6]]


#06-04-2026

In [ ]:
import numpy as np

In [ ]:
#generate an array of indentity matrix
a = np.eye(3,k=1)
print(a)

[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


In [ ]:
b = np.identity(3)
print(b)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#Genarte a range of array and split into equal groups
#np.linspace(start,end,partitions)
c = np.linspace(0,10,6)
print(c)

[ 0.  2.  4.  6.  8. 10.]


**Genarate Random Numbers**

In [ ]:
#generate an random array which is uniformaly distributed 0 to 1, 2rows and 3 columns
a = np.random.random((2,3))
print(a)

[[0.46782101 0.1921155  0.36889745]
 [0.76257725 0.30547105 0.4023574 ]]


In [ ]:
b = np.random.random(5)
print(b)

[0.23546187 0.04597507 0.60199768 0.1166433  0.82306414]


In [ ]:
#generate an arrayt of normally distributed data?
c = np.random.randn(100)
#print(c)
#How can we say a data is normally distributed
#mean is zero and standard deviation is 1
print(c.mean())
print(c.std())

0.01073509028593029
1.0011123481608468


In [ ]:
#generate an normally distributed data with 100 rows and 2 columns
d = np.random.randn(100,2)
print(d)

[[ 0.618388    2.12462541]
 [-0.68683771  0.96531113]
 [ 0.46409838 -0.46256457]
 [ 0.31092519  1.28542385]
 [-0.21154278 -0.00560292]
 [-0.28943449 -0.45069313]
 [-0.34362091  0.52806454]
 [-1.68837247  0.65594938]
 [-0.37701035 -0.50574432]
 [ 0.63989385  1.1965719 ]
 [-0.04643899 -0.54907665]
 [ 0.84714179  0.46366142]
 [ 1.50799967  1.07299749]
 [ 0.20610172 -0.84240504]
 [-0.16710193 -0.41862184]
 [ 1.59875415 -0.97146328]
 [-0.4824023   0.39971216]
 [-1.91920546 -0.53307739]
 [-0.50032698 -0.42355699]
 [-1.05904177  2.07458203]
 [ 1.12920589  0.45959612]
 [ 1.05836892 -0.96981181]
 [-1.34357629  0.11822053]
 [-2.64647255 -0.65217671]
 [ 0.48240263  0.88173827]
 [-2.02572417 -0.32721242]
 [ 0.04768254 -0.16140359]
 [-0.63908019 -2.35547394]
 [ 1.56403991  0.36547476]
 [-0.07556323 -0.16273454]
 [-0.21943147 -1.43511128]
 [-1.06403673  0.62072374]
 [-0.51713396  3.3493108 ]
 [ 0.13264151  0.31298456]
 [ 0.15519436 -0.07259719]
 [ 0.29116094 -1.39333985]
 [ 0.44087093  0.43975755]
 

In [ ]:
#generate an array of random numbers
e = np.random.randint(1,6,size=(2,3))
print(e)

[[4 3 3]
 [1 3 1]]


**solving the linear systems**

In [ ]:
#x1 + x2 = 1200
#2x1 + 3x2 = 6000
#find the values of x1 and x2
a = np.array([[1,1],[2,3]])
b = np.array([1200,6000])
x = np.linalg.solve(a, b)
print(x)

[-2400.  3600.]


1. np.shape --> (rows,col)
2. np.ndim
3. np.size
4. np.dtype
5. np.itemsize -->gives each element occupency in bites
6. what is difference between 1D and 2D array?
  
    --> 1D axis 0 means only rows no columns

    --> 2D have both axis 0 & 1 means rows and columns

7. what is difference between list and array?
8. How van we reshape an array? --> np.reshpe(rows,columns)
9. what is dot product --> vector multiplication and sum of result
    --> np.dot(arr1,aar2)
10. np.zeros((rows,col)) --> generate all zeros with rows and columns
11. np.ones((rows,cols)) --> generate all ones
12. How van we genarte an array specific number --> np.full((rows,cols),num)
13. what is use of copy()? --> np.copy() --> used when we make change in new array it won;t impact on old array
14. How can we apply the conditions in array's --> np.where(logic,true,False)
15. How can we compute the indexes where the condition is true ?-->
np.argwhere(logic)
16. separate an range of array with equal number of parts
np.linspace(start,end,partitions)
17. How can we solve the linear equations --> np.linalg.solve(eq1,eq1)
18. genrate uniformaly distributed array ---> np.random.random((rows,cols))
19. genarte normally distributed array --> np.random.randn((rows,col))
20. generate the integers arrray --> np.random.randint(start,end,size=(rows,cols))

In [ ]:
import numpy as np

l = [10,20,21,45,62,43,26]
#print the even indexes from above list
for i in l:
  print(i%2==0)

True
True
False
False
True
False
True


In [ ]:
a = np.array(l)
b = np.argwhere(a%2==0)
print(b)

[[0]
 [1]
 [4]
 [6]]
