<a href="https://colab.research.google.com/github/Sudarshan0851/python_notes_by_sudarshan/blob/main/pandas_11_Met.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Pandas Introduction**

what is pandas?
> pandas is a open source python libraray that works mainly with labelled data

> Pandas mainly used for Data cleaning, Data anlysis, Data manipulation

> it is like a advance excel 2.o

What is Data cleaning?
> Data cleaning is process that deal with irrelevant rows and columns, data type corrections, handling the null values,handling the duplicates

What is Data Manipulation?
> Data Manipulation means cleaning, tranforming and organizing the data for analysis

what is data analysis?
> Data analysis means oraganising, transforming the data to find some patterns and proecessing the data and interpreting the data to find business insights and supports in decision making

In [ ]:
#Install pandas
!pip install pandas

In [ ]:
#import pandas
import pandas as pd

In [ ]:
#There are 3 types of data structures in pandas
#1. Series :- 1D labelled array
#2. DataFrame :- 2D like tabular format having rows and columns
#3. Panel :- Multidimensional data structures

**Series :- 1D labelled array**

In [ ]:
import numpy as np
a = np.array([1,2,3,4,5,6])
print(a)

[1 2 3 4 5 6]


In [ ]:
#convert the arrays in to series
sr = pd.Series(a)
print(sr)

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64


In [ ]:
sr = pd.Series(a,index=['a','b','c','d','e','f'])
print(sr)

a    1
b    2
c    3
d    4
e    5
f    6
dtype: int64


In [ ]:
#create a series from the set of fruits
s = {"apple",'banana','kiwi'}
sr2 = pd.Series(s)  #set' type is unordered
print(sr2)
#we cannot create a series from the set

TypeError: 'set' type is unordered

In [ ]:
#create a series from dictionary
d = {"name":"medha",
     "address":"Hyderabad"}
sr3 = pd.Series(d)
print(sr3)

name           medha
address    Hyderabad
dtype: object


**DataFrame**

In [ ]:
l = ['apple','banana','kiwi']
#convert list to dataframe
df = pd.DataFrame(l)
print(df)

        0
0   apple
1  banana
2    kiwi


In [ ]:
s = {'apple','banana','kiwi'}
#convert set to df
df1 = pd.DataFrame(s)
print(df1)

        0
0  banana
1   apple
2    kiwi


In [ ]:
d = {"name":"medha",
     "address":"Hyderabad"}
df2 = pd.DataFrame(d,index=["a"])
print(df2)

    name    address
a  medha  Hyderabad


**export and import of Dataframes**

In [ ]:
#read a csv file
df = pd.read_csv("/content/sample_data/california_housing_train.csv")
print(df)

       longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -114.31     34.19                15.0       5612.0          1283.0   
1        -114.47     34.40                19.0       7650.0          1901.0   
2        -114.56     33.69                17.0        720.0           174.0   
3        -114.57     33.64                14.0       1501.0           337.0   
4        -114.57     33.57                20.0       1454.0           326.0   
...          ...       ...                 ...          ...             ...   
16995    -124.26     40.58                52.0       2217.0           394.0   
16996    -124.27     40.69                36.0       2349.0           528.0   
16997    -124.30     41.84                17.0       2677.0           531.0   
16998    -124.30     41.80                19.0       2672.0           552.0   
16999    -124.35     40.54                52.0       1820.0           300.0   

       population  households  median_income  media

In [ ]:
#convert the csv file to the json file
df.to_json("sample.json")

In [ ]:
df2 = pd.read_json("/content/sample.json")
#convert to excel file
df2.to_excel("sample.xlsx")

In [ ]:
df3 = pd.read_excel("/content/sample.xlsx")
df3

,Unnamed: 0,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,0,-114.31,34.19,15,5612,1283,1015,472,1.4936,66900
1,1,-114.47,34.40,19,7650,1901,1129,463,1.8200,80100
2,2,-114.56,33.69,17,720,174,333,117,1.6509,85700
3,3,-114.57,33.64,14,1501,337,515,226,3.1917,73400
4,4,-114.57,33.57,20,1454,326,624,262,1.9250,65500
...,...,...,...,...,...,...,...,...,...,...
16995,16995,-124.26,40.58,52,2217,394,907,369,2.3571,111400
16996,16996,-124.27,40.69,36,2349,528,1194,465,2.5179,79000
16997,16997,-124.30,41.84,17,2677,531,1244,456,3.0313,103600
16998,16998,-124.30,41.80,19,2672,552,1298,478,1.9797,85800


**DataFrame function**

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
data = {
    "patient_id" : [101,102,103,104,105],
    "patient_name":["Ravi","Anita","Jhon",None,"Sara"],
    "age" : [45,50,None,60,55],
    "gender": ["M","f","M","F",None],
    "dialysis_date" :["2026-01-01","2026-01-02",None,"2026-01-04","2026-01-05"],
    "Session_duaration" :[4,3.5,4,None,5],
    "cost":[2000,1800,None,2200,2100],
    "city":["Hyderabad","Chennai","Mumbai",None,"Delhi"]
}
#convert the dictionary into dataframe
df = pd.DataFrame(data)
print(df)

   patient_id patient_name   age gender dialysis_date  Session_duaration  \
0         101         Ravi  45.0      M    2026-01-01                4.0   
1         102        Anita  50.0      f    2026-01-02                3.5   
2         103         Jhon   NaN      M          None                4.0   
3         104         None  60.0      F    2026-01-04                NaN   
4         105         Sara  55.0   None    2026-01-05                5.0   

     cost       city  
0  2000.0  Hyderabad  
1  1800.0    Chennai  
2     NaN     Mumbai  
3  2200.0       None  
4  2100.0      Delhi  


In [ ]:
#check the fist 5 rows of data frame
df.head()

,patient_id,patient_name,age,gender,dialysis_date,Session_duaration,cost,city
0,101,Ravi,45.0,M,2026-01-01,4.0,2000.0,Hyderabad
1,102,Anita,50.0,f,2026-01-02,3.5,1800.0,Chennai
2,103,Jhon,NaN,M,None,4.0,NaN,Mumbai
3,104,None,60.0,F,2026-01-04,NaN,2200.0,None
4,105,Sara,55.0,None,2026-01-05,5.0,2100.0,Delhi


In [ ]:
#check the number of rows and columns in the df
df.shape

(5, 8)

In [ ]:
#check the data types of each column
df.dtypes

,0
patient_id,int64
patient_name,object
age,float64
gender,object
dialysis_date,object
Session_duaration,float64
cost,float64
city,object


In [ ]:
#check the overall information of the data
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   patient_id         5 non-null      int64  
 1   patient_name       4 non-null      object 
 2   age                4 non-null      float64
 3   gender             4 non-null      object 
 4   dialysis_date      4 non-null      object 
 5   Session_duaration  4 non-null      float64
 6   cost               4 non-null      float64
 7   city               4 non-null      object 
dtypes: float64(3), int64(1), object(4)
memory usage: 452.0+ bytes


In [ ]:
#get the descriptive stats of the
df.describe()

,patient_id,age,Session_duaration,cost
count,5.000000,4.000000,4.000000,4.000000
mean,103.000000,52.500000,4.125000,2025.000000
std,1.581139,6.454972,0.629153,170.782513
min,101.000000,45.000000,3.500000,1800.000000
25%,102.000000,48.750000,3.875000,1950.000000
50%,103.000000,52.500000,4.000000,2050.000000
75%,104.000000,56.250000,4.250000,2125.000000
max,105.000000,60.000000,5.000000,2200.000000


In [ ]:
#check the null values in the data frame
df.isnull().sum()

,0
patient_id,0
patient_name,1
age,1
gender,1
dialysis_date,1
Session_duaration,1
cost,1
city,1


**access the data from df**

In [ ]:
#check the patient column
df['patient_name']

,patient_name
0,Ravi
1,Anita
2,Jhon


In [ ]:
#check the column
df.columns

Index(['patient_id', 'patient_name', 'age', 'gender', 'dialysis_date',
       'Session_duaration', 'cost', 'city'],
      dtype='object')

In [ ]:
#access the multiple columns at a time  --> use the double slicing operators
df[['patient_name', 'age', 'gender', 'dialysis_date']]

,patient_name,age,gender,dialysis_date
0,Ravi,45.0,M,2026-01-01
1,Anita,50.0,f,2026-01-02
2,Jhon,NaN,M,None
3,None,60.0,F,2026-01-04
4,Sara,55.0,None,2026-01-05


In [ ]:
#print the 1st 3 rows of above columns
df[['patient_name', 'age', 'gender', 'dialysis_date']].values[0]

array(['Ravi', 45.0, 'M', '2026-01-01'], dtype=object)

**loc and iloc**

> loc is used to locate rows

> iloc is also used to locate data by passing axis numbers

In [ ]:
df['dialysis_date'].loc[1]

'2026-01-02'

In [ ]:
df[['patient_name', 'age', 'gender', 'dialysis_date']].loc[1:4]

,patient_name,age,gender,dialysis_date
1,Anita,50.0,f,2026-01-02
2,Jhon,NaN,M,None
3,None,60.0,F,2026-01-04
4,Sara,55.0,None,2026-01-05


**df.iloc[row_axis,col_axis]**

In [ ]:
df.iloc[0:3,1:4]

,patient_name,age,gender
0,Ravi,45.0,M
1,Anita,50.0,f
2,Jhon,NaN,M


**fill the null values**

In [ ]:
#to fill null values use the df.fillna(value)
df['patient_name'].fillna("unknown",inplace=True)

In [ ]:
#pd.DataFrame()
#df.shape
#df.head()
#df.columns
#df.describe()
#df.info()
#df.loc[start:end:step]
#df.iloc[row_axis,colum_axis]


,patient_name
0,False
1,False
2,False
3,False
4,False


#Doubts

In [ ]:
import numpy as np

In [ ]:
#Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
#hint: np.unravel_index()
print(np.unravel_index(99,(6,7,8)))

#6 --> 6 block
#7 --> rows
#8 --> columns
#--> 6*7*8 -->336 --> 100th

for i in range(1,101):
  print(i,end=" ")

(np.int64(1), np.int64(5), np.int64(3))
1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99 100 

In [ ]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [ ]:
b = np.array([[1,2],[3,4]])
print(b)

[[1 2]
 [3 4]]


In [ ]:
c = np.array([[[1,2],[3,4],[5,6]]])
print(c.shape)
print(c)

(1, 3, 2)
[[[1 2]
  [3 4]
  [5 6]]]


In [ ]:
print(0*np.nan)

nan


In [ ]:
print(np.nan == np.nan)
print(0 == None)

False
False


In [ ]:
print(np.inf > np.nan)

False


In [ ]:
print(np.nan - np.nan)

nan


In [ ]:
print(np.nan in set([np.nan]))

True


In [ ]:
print(0.3 == 3 * 0.1)

False


In [ ]:
print(3*0.1)

0.30000000000000004


In [ ]:
print(sum(range(5),-1))

10


In [ ]:
print(sum(range(5),-1))

#-1,0,1,2,3,4 --> 10 -1

10


#09-04-2026

**Handling the missing data**

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.DataFrame([[1,2,3],[4,np.nan,5],[np.nan,np.nan,np.nan]])
df

,0,1,2
0,1.0,2.0,3.0
1,4.0,NaN,5.0
2,NaN,NaN,NaN


In [ ]:
#How we are going to drop the null values
#df.dropna()
df.dropna()
#The above command removes the rows having null values
#remove only the rows having all null values  --> use "how"

,0,1,2
0,1.0,2.0,3.0


In [ ]:
df.dropna(how="all")

,0,1,2
0,1.0,2.0,3.0
1,4.0,NaN,5.0


In [ ]:
#replace the first index column data with null value
df[1] = np.nan

In [ ]:
#remove the columns which is having alll the null values
df.dropna(axis = 0,how="all")

,0,1,2
0,1.0,NaN,3.0
1,4.0,NaN,5.0


In [ ]:
#thresh :- count of non-null values
df = pd.DataFrame([[1,2,3],[4,np.nan,5],[6,np.nan,np.nan]])
#df.dropna(thresh=2) # in a row count of non null values is 2

In [ ]:
df.dropna(thresh=3,inplace=True)

In [ ]:
df

,0,1,2
0,1,2.0,3.0


In [ ]:
#there is a dataset of 100 rows and 10 columns
#where in the particular row if the null values is >=4 then delete that row
df.dropna(thresh=6)

In [ ]:
##there is a dataset of 100 rows and 10 columns
#if the particular column having 20 null values drop that column
df.dropna(thresh=80,axis=1)

In [ ]:
#df.dropna(axis=0/1,how="all/any",thresh=count,inplace=True/False)

**Fill null values**

In [ ]:
df = pd.DataFrame([[1,2,3],[4,np.nan,5],[np.nan,np.nan,np.nan]])
df

,0,1,2
0,1.0,2.0,3.0
1,4.0,NaN,5.0
2,NaN,NaN,NaN


In [ ]:
#df.fillna(value)
df.fillna(0)

,0,1,2
0,1.0,2.0,3.0
1,4.0,0.0,5.0
2,0.0,0.0,0.0


In [ ]:
df.fillna(df.mean())

,0,1,2
0,1.0,2.0,3.0
1,4.0,2.0,5.0
2,2.5,2.0,4.0


In [ ]:
#fill the null values with front values
df.fillna(method="ffill")

/tmp/ipykernel_4653/1121374958.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method="ffill")


,0,1,2
0,1.0,2.0,3.0
1,4.0,2.0,5.0
2,4.0,2.0,5.0


#10-04-2026

**Data Manipulation in Pandas**

In [ ]:
import pandas as pd
import numpy as np



In [ ]:
df = pd.DataFrame(columns= ['Name','Age','City'])
df

,Name,Age,City


In [ ]:
#insert the data into dataframe
#1. alix,25,delhi
#to insert the data into dataframe use the "loc"
df.loc[0] = ['alix',25,"Delhi"]
df.loc[1] = ['Bunny',26,"Mumbai"]

In [ ]:
print(df)

    Name  Age    City
0   alix   25   Delhi
1  Bunny   26  Mumbai


In [ ]:
#method 2: pd.concat()
new_row = pd.DataFrame([{"Name":"Charlie","Age":25,"City":"Hyderabad"}])
df = pd.concat([df,new_row],ignore_index=True)
df

,Name,Age,City
0,alix,25,Delhi
1,Bunny,26,Mumbai
2,Charlie,25,Hyderabad


**add a column into a DataFrame**

In [ ]:
df['gender'] = ['f','m','m']
df

,Name,Age,City,gender
0,alix,25,Delhi,f
1,Bunny,26,Mumbai,m
2,Charlie,25,Hyderabad,m
